# Generated by Django 5.1.1 on 2024-09-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nome',
        ),
    ]
