# Generated by Django 5.1.1 on 2024-09-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_rename_nome_completo_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes_credito', to='banco.cliente'),
        ),
    ]
